# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UgFBl5kGqgwPhxRLu_Mvb54nhwI2bnBL

**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report 

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()

# Define and bind namespaces consistently needed for data06.ttl and queries
ont = Namespace("http://oeg.fi.upm.es/def/people#") 
p = Namespace("http://oeg.fi.upm.es/resource/person/")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#") 
# Bind prefixes
g.namespace_manager.bind('ont', ont, override=False)
g.namespace_manager.bind('p', p, override=False)
g.namespace_manager.bind('vcard', VCARD, override=False) 
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)


# Parse data file
try:
    g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
    print(f"Graph loaded successfully with {len(g)} triples.")
except Exception as e:
    print(f"ERROR loading graph: {e}")

report = Report()


"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

result = []  
# Query all resources declared as RDFS Class
all_classes = list(g.subjects(RDF.type, RDFS.Class))
print(f"Found {len(all_classes)} RDFS Classes.")

for class_uri in all_classes:
    # Find the direct superclass using g.value (returns None if not found)
    superclass_uri = g.value(subject=class_uri, predicate=RDFS.subClassOf, default=None)
    result.append((class_uri, superclass_uri))

# Visualize the results
print("\n--- Results for Task 7.1a ---")
if not result:
    print("No classes found or processed.")
else:
    for r_tuple in result:
      print(r_tuple)
# Validation
report.validate_07_03(g, result)



"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query_71b = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc }
}
ORDER BY ?c
"""

#  Visualize the results
print("\n--- Results for Task 7.1b ---")
query_results_71b = list(g.query(query_71b))
if not query_results_71b:
    print("SPARQL query 7.1b returned no results.")
else:
    for row in query_results_71b:
      print(row.c, row.sc)

# Validation
report.validate_07_03(g, query_71b)



"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""
individuals = []
processed_classes = set()

# Get all subclasses of Person (including Person itself)
def get_all_subclasses(graph, class_uri):
    """Recursively get all subclasses of a class within the graph"""
    subclasses = set()
    # Direct check to prevent infinite loop if class_uri is None or invalid
    if class_uri is None:
        return subclasses

    subclasses.add(class_uri)
    if class_uri in processed_classes:
        return subclasses
    processed_classes.add(class_uri)

    # Find direct subclasses
    direct_subclasses = graph.subjects(RDFS.subClassOf, class_uri)
    for subclass in direct_subclasses:
         # Check if it's a valid URI and not already processed to prevent cycles
        if isinstance(subclass, (Namespace, Literal)) == False and subclass not in processed_classes :
            subclasses.update(get_all_subclasses(graph, subclass))
    return subclasses

# Get all classes that are Person or subclasses of Person
processed_classes.clear() 
person_classes = get_all_subclasses(g, ont.Person) 
print(f"\nFound classes related to ont:Person: {person_classes}")

# Get all individuals of these classes
if person_classes:
    for person_class_uri in person_classes:
        # Check if person_class_uri is a valid URI before querying
        if isinstance(person_class_uri, (Namespace, Literal)) == False :
            for individual_uri in g.subjects(RDF.type, person_class_uri):
                # Ensure it's not already added and it's a resource URI
                 if individual_uri not in individuals and isinstance(individual_uri, (Namespace, Literal)) == False:
                    individuals.append(individual_uri)

# visualize results 
print("\n--- Results for Task 7.2a ---")
if not individuals:
  print("No individuals found for ont:Person or its subclasses.")
else:
    individuals.sort()
    for i in individuals:
      print(i)

# validation
report.validate_07_03(g, individuals)



"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query_72b = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ont: <http://oeg.fi.upm.es/def/people#> # Uses global binding
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?ind
WHERE {
  ?ind a ?class .
  ?class rdfs:subClassOf* ont:Person . # Correctly uses property path
}
ORDER BY ?ind 
"""

# Visualize
print("\n--- Results for Task 7.2b ---")
query_results_72b = list(g.query(query_72b))
if not query_results_72b:
    print("SPARQL query 7.2b returned no results.")
else:
    for row in query_results_72b:
      print(row.ind)

# Validation
report.validate_07_03(g, query_72b)


"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query_73 = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ont: <http://oeg.fi.upm.es/def/people#> # Adjust if Rocky URI uses 'p:'
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?type
WHERE {
  # [cite_start]Assuming Rocky's URI is ont:Rocky based on user's Task07 file [cite: 2]
  ?entity ont:knows ont:Rocky .
  ?entity rdfs:label ?name . # Get the label as name
  ?entity a ?type .
  # Exclude listing the Class definition itself if 'knows' was mistakenly applied
  FILTER NOT EXISTS { ?entity a rdfs:Class . }
}
ORDER BY ?name 
"""

# Visualize
print("\n--- Results for Task 7.3 ---")
query_results_73 = list(g.query(query_73))
if not query_results_73:
    print("SPARQL query 7.3 returned no results.")
else:
    for row in query_results_73:
      print(row.name, row.type)

# Validation
report.validate_07_03(g, query_73)



"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""


query_74 = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ont: <http://oeg.fi.upm.es/def/people#> # Ensure Dog, has_pet, hasColleague are here
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?name
WHERE {
  # Ensure the entity has a label first
  ?entity rdfs:label ?name .
  {
    # Case 1: Has a colleague who owns a Dog
    ?entity ont:hasColleague ?colleague .
    ?colleague ont:has_pet ?pet . 
    ?pet a ont:Dog . 
  }
  UNION
  {
    # Case 2: Has a colleague -> colleague -> owns a Dog
    ?entity ont:hasColleague ?colleague1 .
    ?colleague1 ont:hasColleague ?colleague2 .
    ?colleague2 ont:has_pet ?pet . 
    ?pet a ont:Dog . 
  }
}
ORDER BY ?name # Optional: Order for consistency
"""

# Visualize
print("\n--- Results for Task 7.4 ---")
query_results_74 = list(g.query(query_74))
if not query_results_74:
    print("SPARQL query 7.4 returned no results.")
else:
    for row in query_results_74:
      print(row.name)

# Validation
report.validate_07_04(g,query_74)
report.save_report("_Task_07")
