# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UgFBl5kGqgwPhxRLu_Mvb54nhwI2bnBL

**Task 06:**
"""

# !pip install rdflib 
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"


"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
import rdflib
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()


"""Create a new class named Researcher"""
ns_mydomain = Namespace("http://mydomain.org#")
g.add((ns_mydomain.Researcher, RDF.type, RDFS.Class))
print("--- Initial Researcher Class ---")
for s, p, o in g.triples((ns_mydomain.Researcher, None, None)):
  print(s,p,o)
print("--- End Initial ---")


"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# Task 6.0: Create new prefixes for "ontology" and "person"
ontology = Namespace("http://oeg.fi.upm.es/def/people#")
person = Namespace("http://oeg.fi.upm.es/resource/person/")
g.namespace_manager.bind('ontology', ontology, override=False)
g.namespace_manager.bind('person', person, override=False)


"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# Create Person class
g.add((ontology.Person, RDF.type, RDFS.Class))
g.add((ontology.Person, RDFS.label, Literal("Person", datatype=XSD.string)))

# Create Professor class
g.add((ontology.Professor, RDF.type, RDFS.Class))
g.add((ontology.Professor, RDFS.subClassOf, ontology.Person))
g.add((ontology.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))

# Create AssociateProfessor class
g.add((ontology.AssociateProfessor, RDF.type, RDFS.Class))
g.add((ontology.AssociateProfessor, RDFS.subClassOf, ontology.Professor))
g.add((ontology.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))

# Create InterimAssociateProfessor class
g.add((ontology.InterimAssociateProfessor, RDF.type, RDFS.Class))
g.add((ontology.InterimAssociateProfessor, RDFS.subClassOf, ontology.AssociateProfessor))
g.add((ontology.InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))

# Create FullProfessor class
g.add((ontology.FullProfessor, RDF.type, RDFS.Class))
g.add((ontology.FullProfessor, RDFS.subClassOf, ontology.Professor))
g.add((ontology.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))

# Visualize the results
print("\n--- Results for Task 6.1 ---")
for s, p_term, o in g:
  if p_term in [RDF.type, RDFS.subClassOf, RDFS.label] and \
     s in [ontology.Person, ontology.Professor, ontology.AssociateProfessor, ontology.InterimAssociateProfessor, ontology.FullProfessor]:
    print(s,p_term,o)

# Validation.
print("\nValidating Task 6.1...")
try:
    r.validate_task_06_01(g)
    print("Task 6.1 Validation Passed (likely)")
except Exception as e:
    print(f"Task 6.1 Validation Error: {e}")


"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# hasColleague property (domain: Person, range: Person)
g.add((ontology.hasColleague, RDF.type, RDF.Property))
g.add((ontology.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))
g.add((ontology.hasColleague, RDFS.domain, ontology.Person))
g.add((ontology.hasColleague, RDFS.range, ontology.Person))

# hasName property (domain: Person, range: Literal)
g.add((ontology.hasName, RDF.type, RDF.Property))
g.add((ontology.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))
g.add((ontology.hasName, RDFS.domain, ontology.Person))
g.add((ontology.hasName, RDFS.range, RDFS.Literal)) 

# hasHomePage property (domain: FullProfessor, range: Literal)
g.add((ontology.hasHomePage, RDF.type, RDF.Property))
g.add((ontology.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))
g.add((ontology.hasHomePage, RDFS.domain, ontology.FullProfessor))
g.add((ontology.hasHomePage, RDFS.range, RDFS.Literal)) 

# Visualize the results
print("\n--- Results for Task 6.2 ---")
for s, p_term, o in g:
    if s in [ontology.hasColleague, ontology.hasName, ontology.hasHomePage]:
        print(s,p_term,o)

# Validation.
print("\nValidating Task 6.2...")
try:
    r.validate_task_06_02(g)
    print("Task 6.2 Validation Passed (likely)")
except Exception as e:
    print(f"Task 6.2 Validation Error: {e}")


"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# Create Oscar (AssociateProfessor)
g.add((person.Oscar, RDF.type, ontology.AssociateProfessor))
g.add((person.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string))) 
g.add((person.Oscar, ontology.hasName, Literal("Óscar Corcho García", datatype=XSD.string)))

# Create Asun (FullProfessor)
g.add((person.Asun, RDF.type, ontology.FullProfessor))
g.add((person.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((person.Asun, ontology.hasHomePage, Literal("http://oeg.fi.upm.es/", datatype=XSD.string)))

# Create Raul (InterimAssociateProfessor)
g.add((person.Raul, RDF.type, ontology.InterimAssociateProfessor))
g.add((person.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

# Add relationships
g.add((person.Oscar, ontology.hasColleague, person.Asun))
g.add((person.Asun, ontology.hasColleague, person.Raul))

# Visualize the results
print("\n--- Results for Task 6.3 ---")
for s, p_term, o in g:
    if s in [person.Oscar, person.Asun, person.Raul]:
        print(s,p_term,o)

# Validation.
print("\nValidating Task 6.3...")
try:
    r.validate_task_06_03(g)
    print("Task 6.3 Validation Passed (likely)")
except Exception as e:
    print(f"Task 6.3 Validation Error: {e}")


"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
FOAF  = Namespace("http://xmlns.com/foaf/0.1/")
g.namespace_manager.bind('vcard-rdf', VCARD, override=False)
g.namespace_manager.bind('foaf', FOAF, override=False)

# Properties to Oscar
g.add((person.Oscar, VCARD.Given, Literal("Oscar", datatype=XSD.string)))
g.add((person.Oscar, VCARD.Family, Literal("Corcho", datatype=XSD.string)))
g.add((person.Oscar, FOAF.EMAIL, Literal("ocorcho@fi.upm.es", datatype=XSD.string)))

# Visualize the results
print("\n--- Results for Task 6.4 (Oscar's details) ---")
for s, p_term, o in g.triples((person.Oscar, None, None)):
  if p_term in [VCARD.Given, VCARD.Family, FOAF.EMAIL]:
    print(s,p_term,o)

# Visualize all triples in the graph now
print("\n--- All Triples in Graph ---")
for s, p_term, o in g:
  print(s,p_term,o)


# Validation.
print("\nValidating Task 6.4...")
try:
    r.validate_task_06_04(g)
    print("Task 6.4 Validation Passed (likely)")
    print("\nSaving final report for Task 06...")
    r.save_report("_Task_06")
    print("Report _Task_06 saved.")
except Exception as e:
    print(f"Task 6.4 Validation or Save Error: {e}")

print("\n--- End of Task 06 ---")
